-- Phase 1 demo seed data for SCN International (20 products).
insert into probuy.primary_sources (code, name, is_active)
values ('SCN', 'SCN International', true)
on conflict (code) do update set name = excluded.name, is_active = excluded.is_active, updated_at = now();
with scn_source as (
    select id from probuy.primary_sources where code = 'SCN'
), seed_locations(code, name, province, country, raw_data) as (
    values
    ('SCN-CA', 'SCN Canada Pricing', 'National', 'CA', '{"source": "price_list_example.xlsx", "notes": "Pricing list scope"}'::jsonb)
    ,('MTL', 'Montreal Distribution Centre', 'QC', 'CA', '{"source": "inventory_list_example.xlsx", "sheet": "MTL"}'::jsonb)
    ,('VAN', 'Vancouver Distribution Centre', 'BC', 'CA', '{"source": "inventory_list_example.xlsx", "sheet": "VAN"}'::jsonb)
    ,('EDM', 'Edmonton Distribution Centre', 'AB', 'CA', '{"source": "inventory_list_example.xlsx", "sheet": "EDM"}'::jsonb)
)
insert into probuy.source_locations (source_id, code, name, province, country, is_active, raw_data)
select s.id, l.code, l.name, l.province, l.country, true, l.raw_data
from seed_locations l cross join scn_source s
on conflict (source_id, code) do update
set name = excluded.name, province = excluded.province, country = excluded.country, is_active = excluded.is_active, raw_data = excluded.raw_data, updated_at = now();

with scn_source as (select id from probuy.primary_sources where code = 'SCN'),
seed_products(source_product_key, source_model_no, brand, manufacturer, product_title_en, description_en, category_en, unit_description_en, product_url, image_url, raw_data) as (
    values
    ('AA639', 'S0112', 'PIP Global Safety', 'PIP Global Safety', 'Uvex® Ultra-spec® 2001 OTG Safety Glasses', null, 'Safety Eyewear', 'Each', null, 'https://cdn.scnindustrial.com/images/131-1170.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AA639", "Brand": "PIP Global Safety", "ManufacturerNumber": "S0112", "Status_MTL": "STOCK", "Status_EDM": "ORDER AS NEEDED", "image_main": "131-1170.jpg", "CategoryEnglishLevel1": "Safety", "CategoryEnglish": "Safety Eyewear", "ProductTitle": "Uvex® Ultra-spec® 2001 OTG Safety Glasses", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:30.71Z", "AttributeName1": "Standard(s) Met", "AttributeValue1": "ANSI Z87+/Meets/Exceeds CSA Z94.3", "AttributeName2": "Lens Tint", "AttributeValue2": "Clear", "AttributeName3": "Lens Coating", "AttributeValue3": "Anti-Scratch"}'::jsonb)
    ,('AB218', 'S2506', 'PIP Global Safety', 'PIP Global Safety', 'Uvex® Astrospec OTG® 3001 Safety Glasses', null, 'Safety Eyewear', 'Each', null, 'https://cdn.scnindustrial.com/images/131-2700.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB218", "Brand": "PIP Global Safety", "ManufacturerNumber": "S2506", "Status_MTL": "ORDER AS NEEDED", "Status_EDM": "ORDER AS NEEDED", "image_main": "131-2700.jpg", "CategoryEnglishLevel1": "Safety", "CategoryEnglish": "Safety Eyewear", "ProductTitle": "Uvex® Astrospec OTG® 3001 Safety Glasses", "UnitDescription": "Each", "Date Last Modified": "2026-03-27T22:26:36.12Z", "AttributeName1": "Standard(s) Met", "AttributeValue1": "ANSI Z87+/Meets/Exceeds CSA Z94.3", "AttributeName2": "Lens Tint", "AttributeValue2": "Grey/Smoke", "AttributeName3": "Lens Coating", "AttributeValue3": "Anti-Scratch"}'::jsonb)
    ,('AB292', 'S2508', 'PIP Global Safety', 'PIP Global Safety', 'Uvex® Astrospec OTG® 3001 Safety Glasses', null, 'Safety Eyewear', 'Each', null, 'https://cdn.scnindustrial.com/images/131-2715.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB292", "Brand": "PIP Global Safety", "ManufacturerNumber": "S2508", "Status_MTL": "STOCK", "Status_EDM": "STOCK", "image_main": "131-2715.jpg", "CategoryEnglishLevel1": "Safety", "CategoryEnglish": "Safety Eyewear", "ProductTitle": "Uvex® Astrospec OTG® 3001 Safety Glasses", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:30.753Z", "AttributeName1": "Standard(s) Met", "AttributeValue1": "ANSI Z87+/Meets/Exceeds CSA Z94.3", "AttributeName2": "Lens Tint", "AttributeValue2": "3.0", "AttributeName3": "Lens Coating", "AttributeValue3": "Anti-Scratch"}'::jsonb)
    ,('AB386', 'S2509', 'PIP Global Safety', 'PIP Global Safety', 'Uvex® Astrospec OTG® 3001 Safety Glasses', null, 'Safety Eyewear', 'Each', null, 'https://cdn.scnindustrial.com/images/131-2720.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB386", "Brand": "PIP Global Safety", "ManufacturerNumber": "S2509", "Status_MTL": "STOCK", "Status_EDM": "ORDER AS NEEDED", "image_main": "131-2720.jpg", "CategoryEnglishLevel1": "Safety", "CategoryEnglish": "Safety Eyewear", "ProductTitle": "Uvex® Astrospec OTG® 3001 Safety Glasses", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:30.777Z", "AttributeName1": "Standard(s) Met", "AttributeValue1": "ANSI Z87+/Meets/Exceeds CSA Z94.3", "AttributeName2": "Lens Tint", "AttributeValue2": "5.0", "AttributeName3": "Lens Coating", "AttributeValue3": "Anti-Scratch"}'::jsonb)
    ,('AB463', 'S364', 'PIP Global Safety', 'PIP Global Safety', 'Uvex® Classic™ Safety Goggles', null, 'Safety Goggles', 'Each', null, 'https://cdn.scnindustrial.com/images/131-3115.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB463", "Brand": "PIP Global Safety", "ManufacturerNumber": "S364", "Status_MTL": "STOCK", "Status_EDM": "ORDER AS NEEDED", "image_main": "131-3115.jpg", "CategoryEnglishLevel1": "Safety", "CategoryEnglish": "Safety Goggles", "ProductTitle": "Uvex® Classic™ Safety Goggles", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:30.797Z"}'::jsonb)
    ,('AB642', '2400F', 'Crews', 'Crews', 'Verdict® Safety Goggles with Foam Lining', null, 'Safety Goggles', 'Each', null, 'https://cdn.scnindustrial.com/images/135-5505.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB642", "Brand": "Crews", "ManufacturerNumber": "2400F", "Status_MTL": "STOCK", "Status_EDM": "ORDER AS NEEDED", "image_main": "135-5505.jpg", "CategoryEnglishLevel1": "Safety", "CategoryEnglish": "Safety Goggles", "ProductTitle": "Verdict® Safety Goggles with Foam Lining", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:31.01Z", "AttributeName1": "Ventilation Type", "AttributeValue1": "Indirect", "AttributeName2": "Lens Tint", "AttributeValue2": "Clear", "AttributeName3": "Standard(s) Met", "AttributeValue3": "ANSI Z87+", "AttributeName4": "Lens Coating", "AttributeValue4": "Anti-Scratch", "AttributeName5": "Band Type", "AttributeValue5": "Elastic"}'::jsonb)
    ,('AB703', '29080', 'Jackson Safety', 'Jackson Safety', 'F50 Moulded Faceshield', null, 'Faceshield Visors', 'Each', null, 'https://cdn.scnindustrial.com/images/138-1074.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB703", "Brand": "Jackson Safety", "ManufacturerNumber": "29080", "Status_MTL": "STOCK", "Status_EDM": "ORDER AS NEEDED", "image_main": "138-1074.jpg", "CategoryEnglishLevel1": "Safety", "CategoryEnglish": "Faceshield Visors", "ProductTitle": "F50 Moulded Faceshield", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:31.05Z", "AttributeName1": "Height", "AttributeValue1": "8\"", "AttributeName2": "Width", "AttributeValue2": "15-1/2\"", "AttributeName3": "Thickness", "AttributeValue3": "0.06\"", "AttributeName4": "Material", "AttributeValue4": "Polycarbonate", "AttributeName5": "Shield Tint", "AttributeValue5": "5.0", "AttributeName6": "Standard(s) Met", "AttributeValue6": "ANSI Z87+/Meets/Exceeds CSA Z94.3"}'::jsonb)
    ,('AB704', '16642', 'Jackson Safety', 'Jackson Safety', 'Light Seal Gasket', null, 'Welding Helmet Parts & Accessories', 'Each', null, 'https://cdn.scnindustrial.com/images/138-1987.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB704", "Brand": "Jackson Safety", "ManufacturerNumber": "16642", "Status_MTL": "STOCK", "Status_EDM": "ORDER AS NEEDED", "image_main": "138-1987.jpg", "CategoryEnglishLevel1": "Welding", "CategoryEnglish": "Welding Helmet Parts & Accessories", "ProductTitle": "Light Seal Gasket", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:31.133Z"}'::jsonb)
    ,('AB705', '8293', '3M', '3M', 'Particulate Respirators 8293', null, 'Disposable Respirators', 'Each', null, 'https://cdn.scnindustrial.com/images/142-8293.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB705", "Brand": "3M", "ManufacturerNumber": "8293", "Status_MTL": "STOCK", "Status_EDM": "STOCK", "image_main": "142-8293.jpg", "CategoryEnglishLevel1": "Safety", "CategoryEnglish": "Disposable Respirators", "ProductTitle": "Particulate Respirators 8293", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:31.29Z", "AttributeName1": "Certification(s)", "AttributeValue1": "NIOSH", "AttributeName2": "Size", "AttributeValue2": "Standard", "AttributeName3": "Style", "AttributeValue3": "Cup", "AttributeName4": "Exhalation Valve", "AttributeValue4": "With", "AttributeName5": "Type", "AttributeValue5": "P100"}'::jsonb)
    ,('AB749', '36292', 'Jackson Safety', 'Jackson Safety', 'Welding Curtain', null, 'Welding Curtains', 'Each', null, 'https://cdn.scnindustrial.com/images/146-1280.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB749", "Brand": "Jackson Safety", "ManufacturerNumber": "36292", "Status_MTL": "STOCK", "Status_EDM": "ORDER AS NEEDED", "image_main": "146-1280.jpg", "CategoryEnglishLevel1": "Welding", "CategoryEnglish": "Welding Curtains", "ProductTitle": "Welding Curtain", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:31.407Z", "AttributeName1": "Colour", "AttributeValue1": "Orange", "AttributeName2": "Dimensions", "AttributeValue2": "72\" x 72\""}'::jsonb)
    ,('AB750', '36302', 'Jackson Safety', 'Jackson Safety', 'Welding Blankets', null, 'Welding Blankets', 'Each', null, 'https://cdn.scnindustrial.com/images/146-3100.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB750", "Brand": "Jackson Safety", "ManufacturerNumber": "36302", "Status_MTL": "STOCK", "Status_EDM": "ORDER AS NEEDED", "image_main": "146-3100.jpg", "CategoryEnglishLevel1": "Welding", "CategoryEnglish": "Welding Blankets", "ProductTitle": "Welding Blankets", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:31.42Z", "AttributeName1": "Dimensions", "AttributeValue1": "6'' W x 6'' L", "AttributeName2": "Weight Per Square Yard", "AttributeValue2": "24 oz.", "AttributeName3": "Temperature Resistance", "AttributeValue3": "1200 F"}'::jsonb)
    ,('AB751', '36307', 'Jackson Safety', 'Jackson Safety', 'Welding Curtain', null, 'Welding Curtains', 'Each', null, 'https://cdn.scnindustrial.com/images/146-1280.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB751", "Brand": "Jackson Safety", "ManufacturerNumber": "36307", "Status_MTL": "STOCK", "Status_EDM": "ORDER AS NEEDED", "image_main": "146-1280.jpg", "CategoryEnglishLevel1": "Welding", "CategoryEnglish": "Welding Curtains", "ProductTitle": "Welding Curtain", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:31.437Z", "AttributeName1": "Colour", "AttributeValue1": "Orange", "AttributeName2": "Dimensions", "AttributeValue2": "96\" x 72\""}'::jsonb)
    ,('AB752', '36318', 'Jackson Safety', 'Jackson Safety', 'Welding Blankets', null, 'Welding Blankets', 'Each', null, 'https://cdn.scnindustrial.com/images/146-3100.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB752", "Brand": "Jackson Safety", "ManufacturerNumber": "36318", "Status_MTL": "STOCK", "Status_EDM": "ORDER AS NEEDED", "image_main": "146-3100.jpg", "CategoryEnglishLevel1": "Welding", "CategoryEnglish": "Welding Blankets", "ProductTitle": "Welding Blankets", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:31.47Z", "AttributeName1": "Dimensions", "AttributeValue1": "6'' W x 8'' L", "AttributeName2": "Weight Per Square Yard", "AttributeValue2": "24 oz.", "AttributeName3": "Temperature Resistance", "AttributeValue3": "1200 F"}'::jsonb)
    ,('AB753', 'QM24PLUS', 'PIP Global Safety', 'PIP Global Safety', 'Howard Leight™ QM24+ Earmuff', null, 'Earmuff', 'Each', null, 'https://cdn.scnindustrial.com/images/154-1205.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB753", "Brand": "PIP Global Safety", "ManufacturerNumber": "QM24PLUS", "Status_MTL": "STOCK", "Status_EDM": "STOCK", "image_main": "154-1205.jpg", "CategoryEnglishLevel1": "Safety", "CategoryEnglish": "Earmuff", "ProductTitle": "Howard Leight™ QM24+ Earmuff", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:32.083Z", "AttributeName1": "Style", "AttributeValue1": "Multi-Position", "AttributeName2": "Meets/Exceeds CSA Class", "AttributeValue2": "A", "AttributeName3": "NRR dB", "AttributeValue3": "25"}'::jsonb)
    ,('AB754', '100QF-Y', 'Gentec', 'Gentec', 'Gas Saver', null, 'Soldering Accessories', 'Each', null, 'https://cdn.scnindustrial.com/images/230-1030.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB754", "Brand": "Gentec", "ManufacturerNumber": "100QF-Y", "Status_MTL": "ORDER AS NEEDED", "Status_EDM": "ORDER AS NEEDED", "image_main": "230-1030.jpg", "CategoryEnglishLevel1": "Welding", "CategoryEnglish": "Soldering Accessories", "ProductTitle": "Gas Saver", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:32.15Z", "AttributeName1": "Type", "AttributeValue1": "For acetylene"}'::jsonb)
    ,('AB755', '6-CO-2', 'Western Enterprises', 'Western Enterprises', 'Regulator Nut', null, 'Gas Welder Fittings', 'Each', null, 'https://cdn.scnindustrial.com/images/312-1052_lr.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB755", "Brand": "Western Enterprises", "ManufacturerNumber": "6-CO-2", "Status_MTL": "ORDER AS NEEDED", "Status_EDM": "ORDER AS NEEDED", "image_main": "312-1052_lr.jpg", "CategoryEnglishLevel1": "Welding", "CategoryEnglish": "Gas Welder Fittings", "ProductTitle": "Regulator Nut", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:33.837Z", "AttributeName1": "Material", "AttributeValue1": "Brass"}'::jsonb)
    ,('AB756', '6-CO-2P', 'Western Enterprises', 'Western Enterprises', 'Regulator Nuts & Nipples', null, 'Gas Welder Fittings', 'Each', null, 'https://cdn.scnindustrial.com/images/312-1052_lr.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB756", "Brand": "Western Enterprises", "ManufacturerNumber": "6-CO-2P", "Status_MTL": "ORDER AS NEEDED", "Status_EDM": "ORDER AS NEEDED", "image_main": "312-1052_lr.jpg", "CategoryEnglishLevel1": "Welding", "CategoryEnglish": "Gas Welder Fittings", "ProductTitle": "Regulator Nuts & Nipples", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:33.857Z", "AttributeName1": "Material", "AttributeValue1": "Brass"}'::jsonb)
    ,('AB757', '6-CO-4', 'Western Enterprises', 'Western Enterprises', 'Regulator Nuts & Nipples', null, 'Gas Welder Fittings', 'Each', null, 'https://cdn.scnindustrial.com/images/312-3106_lr.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB757", "Brand": "Western Enterprises", "ManufacturerNumber": "6-CO-4", "Status_MTL": "ORDER AS NEEDED", "Status_EDM": "ORDER AS NEEDED", "image_main": "312-3106_lr.jpg", "CategoryEnglishLevel1": "Welding", "CategoryEnglish": "Gas Welder Fittings", "ProductTitle": "Regulator Nuts & Nipples", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:33.88Z", "AttributeName1": "Material", "AttributeValue1": "Brass"}'::jsonb)
    ,('AB758', '7', 'Western Enterprises', 'Western Enterprises', 'Hose Nuts', null, 'Gas Welder Fittings', 'Each', null, 'https://cdn.scnindustrial.com/images/312-1060_lr.jpg', '{"Label": "Q22026_345", "LastPullDate": "2026-04-03T08:00:17.057Z", "Prod": "AB758", "Brand": "Western Enterprises", "ManufacturerNumber": "7", "Status_MTL": "STOCK", "Status_EDM": "STOCK", "image_main": "312-1060_lr.jpg", "CategoryEnglishLevel1": "Welding", "CategoryEnglish": "Gas Welder Fittings", "ProductTitle": "Hose Nuts", "UnitDescription": "Each", "Date Last Modified": "2026-04-03T04:02:33.9Z"}'::jsonb)
    ,('131-1510', '131-1510', 'SCN Demo', 'SCN Demo', 'Inventory-only demo item 131-1510', 'Seeded from inventory_list_example.xlsx for demo coverage.', 'Inventory Seed', 'Each', null, null, '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "131-1510", "Stock Status/État des stocks": "DISCONTINUED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
)
insert into probuy.source_products (source_id, source_product_key, source_model_no, brand, manufacturer, product_title_en, description_en, category_en, unit_description_en, product_url, image_url, is_active, raw_data)
select s.id, p.source_product_key, p.source_model_no, p.brand, p.manufacturer, p.product_title_en, p.description_en, p.category_en, p.unit_description_en, p.product_url, p.image_url, true, p.raw_data
from seed_products p cross join scn_source s
on conflict (source_id, source_product_key) do update
set source_model_no = excluded.source_model_no, brand = excluded.brand, manufacturer = excluded.manufacturer, product_title_en = excluded.product_title_en, description_en = excluded.description_en, category_en = excluded.category_en, unit_description_en = excluded.unit_description_en, product_url = excluded.product_url, image_url = excluded.image_url, is_active = excluded.is_active, raw_data = excluded.raw_data, updated_at = now();

insert into probuy.attribute_definitions (canonical_name, display_name, data_type, unit, is_filterable, is_searchable)
values
    ('band_type', 'Band Type', 'text', null, true, true)
  , ('certification_s', 'Certification(s)', 'text', null, true, true)
  , ('colour', 'Colour', 'text', null, true, true)
  , ('dimensions', 'Dimensions', 'text', null, true, true)
  , ('exhalation_valve', 'Exhalation Valve', 'text', null, true, true)
  , ('height', 'Height', 'text', null, true, true)
  , ('lens_coating', 'Lens Coating', 'text', null, true, true)
  , ('lens_tint', 'Lens Tint', 'text', null, true, true)
  , ('material', 'Material', 'text', null, true, true)
  , ('meets_exceeds_csa_class', 'Meets/Exceeds CSA Class', 'text', null, true, true)
  , ('nrr_db', 'NRR dB', 'text', null, true, true)
  , ('shield_tint', 'Shield Tint', 'text', null, true, true)
  , ('size', 'Size', 'text', null, true, true)
  , ('standard_s_met', 'Standard(s) Met', 'text', null, true, true)
  , ('style', 'Style', 'text', null, true, true)
  , ('temperature_resistance', 'Temperature Resistance', 'text', null, true, true)
  , ('thickness', 'Thickness', 'text', null, true, true)
  , ('type', 'Type', 'text', null, true, true)
  , ('ventilation_type', 'Ventilation Type', 'text', null, true, true)
  , ('weight_per_square_yard', 'Weight Per Square Yard', 'text', null, true, true)
  , ('width', 'Width', 'text', null, true, true)
on conflict (canonical_name) do update set display_name = excluded.display_name, data_type = excluded.data_type, unit = excluded.unit, is_filterable = excluded.is_filterable, is_searchable = excluded.is_searchable, updated_at = now();

with scn_source as (select id from probuy.primary_sources where code = 'SCN'),
seed_attribute_values(source_product_key, display_name, value_text, raw_data) as (
    values
    ('AA639', 'Standard(s) Met', 'ANSI Z87+/Meets/Exceeds CSA Z94.3', '{"attribute_name": "Standard(s) Met", "attribute_value": "ANSI Z87+/Meets/Exceeds CSA Z94.3", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AA639', 'Lens Tint', 'Clear', '{"attribute_name": "Lens Tint", "attribute_value": "Clear", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AA639', 'Lens Coating', 'Anti-Scratch', '{"attribute_name": "Lens Coating", "attribute_value": "Anti-Scratch", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB218', 'Standard(s) Met', 'ANSI Z87+/Meets/Exceeds CSA Z94.3', '{"attribute_name": "Standard(s) Met", "attribute_value": "ANSI Z87+/Meets/Exceeds CSA Z94.3", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB218', 'Lens Tint', 'Grey/Smoke', '{"attribute_name": "Lens Tint", "attribute_value": "Grey/Smoke", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB218', 'Lens Coating', 'Anti-Scratch', '{"attribute_name": "Lens Coating", "attribute_value": "Anti-Scratch", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB292', 'Standard(s) Met', 'ANSI Z87+/Meets/Exceeds CSA Z94.3', '{"attribute_name": "Standard(s) Met", "attribute_value": "ANSI Z87+/Meets/Exceeds CSA Z94.3", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB292', 'Lens Tint', '3.0', '{"attribute_name": "Lens Tint", "attribute_value": "3.0", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB292', 'Lens Coating', 'Anti-Scratch', '{"attribute_name": "Lens Coating", "attribute_value": "Anti-Scratch", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB386', 'Standard(s) Met', 'ANSI Z87+/Meets/Exceeds CSA Z94.3', '{"attribute_name": "Standard(s) Met", "attribute_value": "ANSI Z87+/Meets/Exceeds CSA Z94.3", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB386', 'Lens Tint', '5.0', '{"attribute_name": "Lens Tint", "attribute_value": "5.0", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB386', 'Lens Coating', 'Anti-Scratch', '{"attribute_name": "Lens Coating", "attribute_value": "Anti-Scratch", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB642', 'Ventilation Type', 'Indirect', '{"attribute_name": "Ventilation Type", "attribute_value": "Indirect", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB642', 'Lens Tint', 'Clear', '{"attribute_name": "Lens Tint", "attribute_value": "Clear", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB642', 'Standard(s) Met', 'ANSI Z87+', '{"attribute_name": "Standard(s) Met", "attribute_value": "ANSI Z87+", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB642', 'Lens Coating', 'Anti-Scratch', '{"attribute_name": "Lens Coating", "attribute_value": "Anti-Scratch", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB642', 'Band Type', 'Elastic', '{"attribute_name": "Band Type", "attribute_value": "Elastic", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB703', 'Height', '8"', '{"attribute_name": "Height", "attribute_value": "8\"", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB703', 'Width', '15-1/2"', '{"attribute_name": "Width", "attribute_value": "15-1/2\"", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB703', 'Thickness', '0.06"', '{"attribute_name": "Thickness", "attribute_value": "0.06\"", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB703', 'Material', 'Polycarbonate', '{"attribute_name": "Material", "attribute_value": "Polycarbonate", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB703', 'Shield Tint', '5.0', '{"attribute_name": "Shield Tint", "attribute_value": "5.0", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB703', 'Standard(s) Met', 'ANSI Z87+/Meets/Exceeds CSA Z94.3', '{"attribute_name": "Standard(s) Met", "attribute_value": "ANSI Z87+/Meets/Exceeds CSA Z94.3", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB705', 'Certification(s)', 'NIOSH', '{"attribute_name": "Certification(s)", "attribute_value": "NIOSH", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB705', 'Size', 'Standard', '{"attribute_name": "Size", "attribute_value": "Standard", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB705', 'Style', 'Cup', '{"attribute_name": "Style", "attribute_value": "Cup", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB705', 'Exhalation Valve', 'With', '{"attribute_name": "Exhalation Valve", "attribute_value": "With", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB705', 'Type', 'P100', '{"attribute_name": "Type", "attribute_value": "P100", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB749', 'Colour', 'Orange', '{"attribute_name": "Colour", "attribute_value": "Orange", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB749', 'Dimensions', '72" x 72"', '{"attribute_name": "Dimensions", "attribute_value": "72\" x 72\"", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB750', 'Dimensions', '6'' W x 6'' L', '{"attribute_name": "Dimensions", "attribute_value": "6'' W x 6'' L", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB750', 'Weight Per Square Yard', '24 oz.', '{"attribute_name": "Weight Per Square Yard", "attribute_value": "24 oz.", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB750', 'Temperature Resistance', '1200 F', '{"attribute_name": "Temperature Resistance", "attribute_value": "1200 F", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB751', 'Colour', 'Orange', '{"attribute_name": "Colour", "attribute_value": "Orange", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB751', 'Dimensions', '96" x 72"', '{"attribute_name": "Dimensions", "attribute_value": "96\" x 72\"", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB752', 'Dimensions', '6'' W x 8'' L', '{"attribute_name": "Dimensions", "attribute_value": "6'' W x 8'' L", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB752', 'Weight Per Square Yard', '24 oz.', '{"attribute_name": "Weight Per Square Yard", "attribute_value": "24 oz.", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB752', 'Temperature Resistance', '1200 F', '{"attribute_name": "Temperature Resistance", "attribute_value": "1200 F", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB753', 'Style', 'Multi-Position', '{"attribute_name": "Style", "attribute_value": "Multi-Position", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB753', 'Meets/Exceeds CSA Class', 'A', '{"attribute_name": "Meets/Exceeds CSA Class", "attribute_value": "A", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB753', 'NRR dB', '25', '{"attribute_name": "NRR dB", "attribute_value": "25", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB754', 'Type', 'For acetylene', '{"attribute_name": "Type", "attribute_value": "For acetylene", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB755', 'Material', 'Brass', '{"attribute_name": "Material", "attribute_value": "Brass", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB756', 'Material', 'Brass', '{"attribute_name": "Material", "attribute_value": "Brass", "source": "contentLicensing_example.xlsx"}'::jsonb)
    ,('AB757', 'Material', 'Brass', '{"attribute_name": "Material", "attribute_value": "Brass", "source": "contentLicensing_example.xlsx"}'::jsonb)
)
insert into probuy.product_attribute_values (source_product_id, attribute_id, value_text, unit, raw_data)
select sp.id, ad.id, sav.value_text, null, sav.raw_data
from seed_attribute_values sav
join scn_source s on true
join probuy.source_products sp on sp.source_id = s.id and sp.source_product_key = sav.source_product_key
join probuy.attribute_definitions ad on ad.display_name = sav.display_name
on conflict (source_product_id, attribute_id) do update
set value_text = excluded.value_text, unit = excluded.unit, raw_data = excluded.raw_data, updated_at = now();

with scn_source as (select id from probuy.primary_sources where code = 'SCN'),
pricing_location as (select sl.id from probuy.source_locations sl join scn_source s on sl.source_id=s.id where sl.code = 'SCN-CA'),
seed_prices(source_product_key, model_no, list_price, distributor_cost, msrp, currency_code, pricing_update_date, raw_data) as (
    values
    ('AA639', 'AA639', 24.90000, 19.42, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AA639", "English Description/Description anglais": "Heavy-Duty Lithium Grease", "List Price/Prix Liste": "24.90000", "Distributor Cost/Coût distributeur": "19.42", "Status/État des stocks": "Stock", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB218', 'AB218', 99999.01000, 99999.01, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB218", "English Description/Description anglais": "2-Feed Gravity Oiler", "List Price/Prix Liste": "99999.01000", "Distributor Cost/Coût distributeur": "99999.01", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB292', 'AB292', 16.00000, 12.80, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB292", "English Description/Description anglais": "Gloozit<sup>®</sup> Sealant", "List Price/Prix Liste": "16.00000", "Distributor Cost/Coût distributeur": "12.80", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB386', 'AB386', 459.00000, 316.71, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB386", "English Description/Description anglais": "Cimguard 10 Corrosion Preventive, Aerosol Can", "List Price/Prix Liste": "459.00000", "Distributor Cost/Coût distributeur": "316.71", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Can"}'::jsonb)
    ,('AB463', 'AB463', 84.90000, 67.07, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB463", "English Description/Description anglais": "CIMCLEAN<sup>®</sup> 30 Cleaner, 1 gal./1.0 gal., Jug", "List Price/Prix Liste": "84.90000", "Distributor Cost/Coût distributeur": "67.07", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Bottle"}'::jsonb)
    ,('AB642', 'AB642', 213.00000, 153.36, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB642", "English Description/Description anglais": "No Skidding<sup>®</sup> Aqua Tuff Slip-Resistant Floor Coating, 1 gal., Water-Based, Clear", "List Price/Prix Liste": "213.00000", "Distributor Cost/Coût distributeur": "153.36", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB703', 'AB703', 25.80000, 20.12, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB703", "English Description/Description anglais": "No Skidding<sup>®</sup> Slip-Resistant Floor Coating, 12 oz., Epoxy-Based, Textured, Grey", "List Price/Prix Liste": "25.80000", "Distributor Cost/Coût distributeur": "20.12", "Status/État des stocks": "Stock", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Can"}'::jsonb)
    ,('AB704', 'AB704', 26.60000, 20.75, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB704", "English Description/Description anglais": "No Skidding<sup>®</sup> Slip-Resistant Floor Coating, 12 oz., Epoxy-Based, Textured, Black", "List Price/Prix Liste": "26.60000", "Distributor Cost/Coût distributeur": "20.75", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Can"}'::jsonb)
    ,('AB705', 'AB705', 30.70000, 23.95, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB705", "English Description/Description anglais": "No Skidding<sup>®</sup> Slip-Resistant Floor Coating, 12 oz., Epoxy-Based, Textured, Yellow", "List Price/Prix Liste": "30.70000", "Distributor Cost/Coût distributeur": "23.95", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Can"}'::jsonb)
    ,('AB749', 'AB749', 504.00000, 332.64, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB749", "English Description/Description anglais": "E-30 Protective Coating, Clear, 25 lbs., B", "List Price/Prix Liste": "504.00000", "Distributor Cost/Coût distributeur": "332.64", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB750', 'AB750', 504.00000, 332.64, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB750", "English Description/Description anglais": "E-30 Protective Coating, Green, 25 lbs., B", "List Price/Prix Liste": "504.00000", "Distributor Cost/Coût distributeur": "332.64", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB751', 'AB751', 504.00000, 332.64, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB751", "English Description/Description anglais": "E-30 Protective Coating, Blue, 25 lbs., B", "List Price/Prix Liste": "504.00000", "Distributor Cost/Coût distributeur": "332.64", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB752', 'AB752', 504.00000, 332.64, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB752", "English Description/Description anglais": "E-30 Protective Coating, Red, 25 lbs., B", "List Price/Prix Liste": "504.00000", "Distributor Cost/Coût distributeur": "332.64", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB753', 'AB753', 436.00000, 287.76, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB753", "English Description/Description anglais": "B-52 Protective Coating, Clear, 25 lbs., B", "List Price/Prix Liste": "436.00000", "Distributor Cost/Coût distributeur": "287.76", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB754', 'AB754', 436.00000, 287.76, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB754", "English Description/Description anglais": "B-52 Protective Coating, Green, 25 lbs., B", "List Price/Prix Liste": "436.00000", "Distributor Cost/Coût distributeur": "287.76", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB755', 'AB755', 436.00000, 287.76, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB755", "English Description/Description anglais": "B-52 Protective Coating, Blue, 25 lbs., B", "List Price/Prix Liste": "436.00000", "Distributor Cost/Coût distributeur": "287.76", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB756', 'AB756', 436.00000, 287.76, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB756", "English Description/Description anglais": "B-52 Protective Coating, Red, 25 lbs., B", "List Price/Prix Liste": "436.00000", "Distributor Cost/Coût distributeur": "287.76", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB757', 'AB757', 331.00000, 218.46, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB757", "English Description/Description anglais": "K-25 Protective Coating, Clear, 25 lbs., B", "List Price/Prix Liste": "331.00000", "Distributor Cost/Coût distributeur": "218.46", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
    ,('AB758', 'AB758', 331.00000, 218.46, null, 'CAD', '2026-04-23T00:00:00Z', '{"Model No./No modèle": "AB758", "English Description/Description anglais": "K-25 Protective Coating, Green, 25 lbs., B", "List Price/Prix Liste": "331.00000", "Distributor Cost/Coût distributeur": "218.46", "Status/État des stocks": "Order As Needed", "Pricing Update Date/Dernière mise à jour de prix": "2026-04-23T00:00:00Z", "Unit of Sale": "Each"}'::jsonb)
)
insert into probuy.source_product_prices (source_product_id, location_id, model_no, list_price, distributor_cost, msrp, currency_code, pricing_update_date, effective_at, raw_data)
select sp.id, pl.id, p.model_no, p.list_price::numeric(12,2), p.distributor_cost::numeric(12,2), p.msrp, p.currency_code, p.pricing_update_date::timestamptz, p.pricing_update_date::timestamptz, p.raw_data
from seed_prices p
join scn_source s on true
join probuy.source_products sp on sp.source_id = s.id and sp.source_product_key = p.source_product_key
join pricing_location pl on true
on conflict (source_product_id, location_id) do update
set model_no = excluded.model_no, list_price = excluded.list_price, distributor_cost = excluded.distributor_cost, msrp = excluded.msrp, currency_code = excluded.currency_code, pricing_update_date = excluded.pricing_update_date, effective_at = excluded.effective_at, raw_data = excluded.raw_data, updated_at = now();

with scn_source as (select id from probuy.primary_sources where code = 'SCN'),
seed_inventory(location_code, source_product_key, model_no, stock_status, quantity_available, inventory_update_date, raw_data) as (
    values
    ('MTL', 'AA639', 'AA639', 'STOCK', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AA639", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB218', 'AB218', 'DISCONTINUED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB218", "Stock Status/État des stocks": "DISCONTINUED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB292', 'AB292', 'DISCONTINUED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB292", "Stock Status/État des stocks": "DISCONTINUED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB386', 'AB386', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB386", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB463', 'AB463', 'STOCK', 28, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB463", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "28", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB642', 'AB642', 'STOCK', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB642", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB703', 'AB703', 'STOCK', 23, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB703", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "23", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB704', 'AB704', 'DISCONTINUED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB704", "Stock Status/État des stocks": "DISCONTINUED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB705', 'AB705', 'STOCK', 18, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB705", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "18", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB749', 'AB749', 'STOCK', 2, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB749", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "2", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB750', 'AB750', 'DISCONTINUED', 38, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB750", "Stock Status/État des stocks": "DISCONTINUED", "Quantity Available/Quantité disponible": "38", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB751', 'AB751', 'DISCONTINUED', 136, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB751", "Stock Status/État des stocks": "DISCONTINUED", "Quantity Available/Quantité disponible": "136", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB752', 'AB752', 'STOCK', 3, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB752", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "3", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB753', 'AB753', 'DISCONTINUED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB753", "Stock Status/État des stocks": "DISCONTINUED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB754', 'AB754', 'STOCK', 1226, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB754", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "1226", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB755', 'AB755', 'STOCK', 2, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB755", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "2", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB756', 'AB756', 'STOCK', 8, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB756", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "8", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB757', 'AB757', 'STOCK', 11, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB757", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "11", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('MTL', 'AB758', 'AB758', 'STOCK', 4, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "MTL", "row": {"Model No./No modèle": "AB758", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "4", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AA639', '131-1170', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "131-1170", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AB218', '131-2700', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "131-2700", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AB292', '131-2715', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "131-2715", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AB386', '131-2720', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "131-2720", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AB463', '131-3115', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "131-3115", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AB642', '135-5505', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "135-5505", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AB703', '138-1074', 'STOCK', 3, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "138-1074", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "3", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AB704', '138-1987', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "138-1987", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AB705', '142-8293', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "142-8293", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AB749', '146-1280', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "146-1280", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AB751', '146-1280', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "146-1280", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AB753', '154-1205', 'STOCK', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "154-1205", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', 'AB754', '230-1030', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "230-1030", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('VAN', '131-1510', '131-1510', 'DISCONTINUED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "VAN", "row": {"Model No./No modèle": "131-1510", "Stock Status/État des stocks": "DISCONTINUED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AA639', '131-1170', 'ORDER AS NEEDED', 17, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "131-1170", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "17", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AB218', '131-2700', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "131-2700", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AB292', '131-2715', 'STOCK', 16, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "131-2715", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "16", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AB386', '131-2720', 'ORDER AS NEEDED', 6, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "131-2720", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "6", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AB463', '131-3115', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "131-3115", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AB642', '135-5505', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "135-5505", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AB703', '138-1074', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "138-1074", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AB704', '138-1987', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "138-1987", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AB705', '142-8293', 'STOCK', 20, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "142-8293", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "20", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AB749', '146-1280', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "146-1280", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AB751', '146-1280', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "146-1280", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AB753', '154-1205', 'STOCK', 40, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "154-1205", "Stock Status/État des stocks": "STOCK", "Quantity Available/Quantité disponible": "40", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', 'AB754', '230-1030', 'ORDER AS NEEDED', 0, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "230-1030", "Stock Status/État des stocks": "ORDER AS NEEDED", "Quantity Available/Quantité disponible": "0", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
    ,('EDM', '131-1510', '131-1510', 'DISCONTINUED', 1, '2026-04-23T00:00:00Z', '{"source": "inventory_list_example.xlsx", "sheet": "EDM", "row": {"Model No./No modèle": "131-1510", "Stock Status/État des stocks": "DISCONTINUED", "Quantity Available/Quantité disponible": "1", "Inventory Update Date/Date de mise à jour de l''inventaire": "2026-04-23T00:00:00Z"}}'::jsonb)
)
insert into probuy.source_product_inventory (source_product_id, location_id, model_no, stock_status, quantity_available, inventory_update_date, raw_data)
select sp.id, sl.id, si.model_no, si.stock_status, si.quantity_available::numeric(14,3), si.inventory_update_date::timestamptz, si.raw_data
from seed_inventory si
join scn_source s on true
join probuy.source_locations sl on sl.source_id = s.id and sl.code = si.location_code
join probuy.source_products sp on sp.source_id = s.id and sp.source_product_key = si.source_product_key
on conflict (source_product_id, location_id) do update
set model_no = excluded.model_no, stock_status = excluded.stock_status, quantity_available = excluded.quantity_available, inventory_update_date = excluded.inventory_update_date, raw_data = excluded.raw_data, updated_at = now();

with attribute_json as (
    select pav.source_product_id, jsonb_object_agg(ad.canonical_name, coalesce(pav.value_text, pav.value_numeric::text, pav.value_boolean::text)) as attributes
    from probuy.product_attribute_values pav
    join probuy.attribute_definitions ad on ad.id = pav.attribute_id
    group by pav.source_product_id
), scn_products as (
    select sp.id, sp.brand, sp.manufacturer, sp.source_model_no, sp.category_en, sp.product_title_en, sp.description_en
    from probuy.source_products sp
    join probuy.primary_sources ps on ps.id = sp.source_id
    where ps.code = 'SCN' and sp.is_active = true
)
insert into probuy.product_search_documents (source_product_id, search_text, search_vector, brand, manufacturer, model_no, category, attributes)
select p.id,
       trim(concat_ws(' ', p.product_title_en, p.description_en, p.brand, p.manufacturer, p.source_model_no, p.category_en, coalesce((select string_agg(value, ' ') from jsonb_each_text(coalesce(a.attributes, '{}'::jsonb))), ''))) as search_text,
       to_tsvector('simple', trim(concat_ws(' ', p.product_title_en, p.description_en, p.brand, p.manufacturer, p.source_model_no, p.category_en, coalesce((select string_agg(value, ' ') from jsonb_each_text(coalesce(a.attributes, '{}'::jsonb))), '')))),
       p.brand, p.manufacturer, p.source_model_no, p.category_en, coalesce(a.attributes, '{}'::jsonb)
from scn_products p
left join attribute_json a on a.source_product_id = p.id
on conflict (source_product_id) do update
set search_text = excluded.search_text,
    search_vector = excluded.search_vector,
    brand = excluded.brand,
    manufacturer = excluded.manufacturer,
    model_no = excluded.model_no,
    category = excluded.category,
    attributes = excluded.attributes,
    updated_at = now();
